# Generated by Django 4.0.6 on 2022-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TEAMLEAD', 'team leader'), ('SENIOR', 'senior developer'), ('MIDDLE', 'middle developer'), ('JUNIOR', 'junior developer'), ('TRAINEE', 'trainee')], max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('joinDate', models.DateTimeField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
    ]
