# Generated by Django 4.0.6 on 2022-07-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
